version: "3.7"

services:
    rd-ping-service:
        container_name: rd-ping-service
        image: rd-ping-service
        networks:
            - rd-net
        ports:
            - "3001:3001"
    nginx:
        image: nginx:latest
        container_name: nginx
        networks:
            - rd-net
        ports:
            - "80:80"
            - "443:443"
            - "8002:8002"
        volumes:
            - ../nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
    rd-net:
